#
# SPDX-License-Identifier:  GPL-2.0+
#

obj-y += a1006.o
obj-y += a100x_crypto.mod
obj-y += a100x_host.mod
obj-y += bECC.mod
obj-y += entropy.mod
obj-y += entropy_hal.mod
obj-y += sha224.mod
obj-y += sha224_extra.mod
obj-y += uECC.mod
obj-y += ustrmatch.mod
obj-y += md5.mod
